### ISSUE TITLE
Feature: Add Image Size Threshold for Cleanup

### ISSUE THREAD

**Issue by mmuazam98** [mmuazam98/dockclean#3]
- **Description:** Introduce an option to delete Docker images larger than a specified size. Users can pass a flag like --larger-than 500MB to remove images above the given size limit.
- **Example:**
```bash
./dockclean --larger-than 500MB
```

**Comment by deexithparand** [comment]
Hi @mmuazam98, could you also assign this one to me.

**Comment by deexithparand** [comment]
Hi @mmuazam98, I've completed this issue #12 too, could you please review and merge this ASAP.

I'll update you soon on the issue #6 

Thanks!
