### ISSUE TITLE
Feature: Remove Images Associated with Stopped Containers

### ISSUE THREAD

**Issue by mmuazam98** [mmuazam98/dockclean#4]
- **Description:** Add an option to clean up images associated with containers that have been stopped. This would be especially useful in environments where containers are stopped frequently.
- **Example:**
```bash
./dockclean --remove-stopped
```

**Comment by deexithparand** [comment]
Hi @mmuazam98, I would love to solve this issue too. Could you assign this issue to me.

**Comment by deexithparand** [comment]
Hi @mmuazam98, can we close this issue now since you’ve already merged the PR?
