### ISSUE TITLE
Feature: Parallel Image Deletion

### ISSUE THREAD

**Issue by mmuazam98** [mmuazam98/dockclean#6]
**Description:** Speed up the cleanup process by deleting images in parallel using Go routines. Introduce concurrency for faster removal of a large number of unused images.

**Comment by deexithparand** [comment]
Hi @mmuazam98, I would love to contribute to this project. Can you assign this issue to me.

**Comment by deexithparand** [comment]
Hi @mmuazam98 ,

I've completed the work on issue #13. Could you please review and merge this PR if everything looks good? I'll also update the README for the four issues I've completed, as we discussed.

Thanks!

**Comment by deexithparand** [comment]
Thank you, @mmuazam98 , for consistently merging all my PRs on time. 

This is my second **Hacktoberfest**, and contributing to a **Golang** repository was a key goal for me—it’s been a great experience to see that come true with **dockclean**. 

I really appreciate the opportunity and your responsiveness throughout the process.

Your work has been truly inspiring, and I look forward to contributing further to this repository and any of your future projects.

Thanks again!

**Comment by mmuazam98** [comment]
@deexithparand 
You’re very welcome! I’m glad I could help make your Hacktoberfest experience a fulfilling one. It’s been great having your contributions to dockclean, and I’m really impressed by your dedication and attention to detail. I look forward to seeing more of your work in this project and beyond. Thank you!
